apiVersion: v1
kind: Pod
metadata:
  name: app-with-secret
  namespace: default
  labels:
    app: demo-app
spec:
  containers:
  - name: app
    image: nginx:alpine
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: password
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: host
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secrets
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: db-secret
