apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default
type: Opaque
stringData:
  username: admin
  password: SuperSecret123!
  host: postgres.production.svc.cluster.local
  port: "5432"
