apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-role
  namespace: default
rules:
# Allow getting, listing, and watching pods
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
# Allow getting and listing services
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
# Allow reading ConfigMaps (but not Secrets!)
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
