## Node.js 20 Alpine - Current LTS with minimal attack surface ##
## Alpine Linux provides a minimal base image with active security support ##
apiVersion: v1
kind: Pod
metadata:
  name: safe-curl-demo
  labels:
    app: safe-curl-demo
spec:
  containers:
    - name: curl-container
      image: curlimages/curl:8.17.0@sha256:935d9100e9ba842cdb060de42472c7ca90cfe9a7c96e4dacb55e79e560b3ff40
      command: ["/bin/sh", "-c", "sleep 3600"]
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
