## DO NOT DEPLOY THIS POD IN PRODUCTION ##
## Image contains known vulnerabilities for demonstration purposes only ##
## Node.js 10 reached End of Life (EOL) in April 2021 - no security updates ##
apiVersion: v1
kind: Pod
metadata:
  name: vulnerable-curl-demo
  labels:
    app: vulnerable-curl-demo
spec:
  containers:
    - name: curl-container
      image: curlimages/curl:7.82.0
      command: ["/bin/sh", "-c", "sleep 3600"]
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
