## DO NOT DEPLOY THIS POD IN PRODUCTION ##
## Image contains known vulnerabilities for demonstration purposes only ##
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-demo
  labels:
    app: ubuntu-demo
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:22.04
      command: ["/bin/bash", "-c", "sleep 3600"]
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
